/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NnTooltip {
        "for": string;
        "text": string;
    }
}
declare global {
    interface HTMLNnTooltipElement extends Components.NnTooltip, HTMLStencilElement {
    }
    var HTMLNnTooltipElement: {
        prototype: HTMLNnTooltipElement;
        new (): HTMLNnTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "nn-tooltip": HTMLNnTooltipElement;
    }
}
declare namespace LocalJSX {
    interface NnTooltip {
        "for"?: string;
        "text"?: string;
    }
    interface IntrinsicElements {
        "nn-tooltip": NnTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nn-tooltip": LocalJSX.NnTooltip & JSXBase.HTMLAttributes<HTMLNnTooltipElement>;
        }
    }
}
